services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - .:/root/.ollama
    networks:
      - ai-net
    restart: unless-stopped
  
  # side-car metrics
  ollama-exporter:
    image: prom/node-exporter:latest
    container_name: ollama-exporter
    pid: host
    network_mode: host
    command:
      - --collector.processes
      - --web.listen-address=:9113
    restart: unless-stopped

networks:
  ai-net:
    external: true