services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
      - "9090:9090"
    volumes:
      - .:/root/.ollama
    networks:
      - ai-net
    restart: unless-stopped
    environment:
      - OLLAMA_PROMETHEUS_ENABLED=true
      - OLLAMA_PROMETHEUS_PORT=9090

networks:
  ai-net:
    external: true
