services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.56.1-jammy
    container_name: playwright
    working_dir: /app
    volumes:
      - ./playwright:/app
    command: ["npm", "start"]
    ports:
      - "3100:3000"
    restart: unless-stopped

  playwright-exporter:
    image: prom/node-exporter:latest
    container_name: playwright-exporter
    pid: host
    network_mode: host
    command:
      - --collector.processes
      - --web.listen-address=:9115
    restart: unless-stopped